name: Build Chocolatey Package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  issues: write

jobs:
  test:
    uses: ./.github/workflows/check-lgpo.yml

  build:
    needs: test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        shell: pwsh
      
      - name: Build Package
        run: |
          choco pack
        shell: pwsh
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: '*.nupkg'
          
      - name: Extract package info
        id: package-info
        shell: pwsh
        run: |
          $nuspec = [xml](Get-Content lgpo.nuspec)
          $version = $nuspec.package.metadata.version
          $id = $nuspec.package.metadata.id
          "package-id=$id" >> $env:GITHUB_OUTPUT
          "package-version=$version" >> $env:GITHUB_OUTPUT
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '*.nupkg'
          name: "${{ steps.package-info.outputs.package-id }} v${{ steps.package-info.outputs.package-version }}"
          body: "Release of ${{ steps.package-info.outputs.package-id }} version ${{ steps.package-info.outputs.package-version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
