name: publish-to-chocolatey

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    environment: chocolatey

    steps:
      - uses: actions/checkout@v4

      - name: Determine latest release tag
        id: latest
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $repo = $env:GITHUB_REPOSITORY
          $tag  = gh api "repos/$repo/releases/latest" --jq ".tag_name"
          if (-not $tag) { throw "Could not determine latest release tag for $repo" }
          "tag=$tag" >> $env:GITHUB_OUTPUT
          Write-Host "Latest release tag: $tag"

      - name: (Debug) List assets on latest release
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view ${{ steps.latest.outputs.tag }} --json assets --jq '.assets[].name'

      - name: Download .nupkg from latest release
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download ${{ steps.latest.outputs.tag }} -p "*.nupkg" -D dist
          if (-not (Test-Path dist)) { throw "No assets downloaded. Does the latest release have a .nupkg attached?" }
          $pkgs = Get-ChildItem dist\*.nupkg
          if (-not $pkgs) { throw "No .nupkg files found in the latest release assets." }
          $pkgs | Format-Table Name,Length,LastWriteTime

      - name: Push to Chocolatey
        shell: pwsh
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        run: |
          choco apikey --key $env:CHOCO_API_KEY --source https://push.chocolatey.org/
          $nupkg = Get-ChildItem dist\*.nupkg | Select-Object -First 1
          if (-not $nupkg) { throw "No .nupkg found to push." }
          Write-Host "Pushing $($nupkg.FullName) to Chocolatey…"
          choco push $nupkg.FullName --source https://push.chocolatey.org/
