name: publish-to-chocolatey

on:
  workflow_run:
    workflows: ["build-and-release"]   # name of your build workflow
    types: [completed]

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact from triggering run
        uses: actions/download-artifact@v4
        with:
          name: nupkg
          run-id: ${{ github.event.workflow_run.id }}

      - name: Push to Chocolatey
        shell: pwsh
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        run: |
          choco apikey --key $env:CHOCO_API_KEY --source https://push.chocolatey.org/
          $nupkg = Get-ChildItem *.nupkg | Select-Object -First 1
          choco push $nupkg --source https://push.chocolatey.org/
